# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 92bf8270cdc3a14ed61254729fed10ce553e9f018279b0d712d24937ad30c678e917b22bbb2ca40151b4dee1fb863ce3216f3f5e9701bfaccde204662c1338b9

test:
  secret_key_base: 16177024c544aa7b0e2741ef174b1b819bc0e8a93209174544abedbc294f7e2708272948fa592a8f4357ddd997d2eb052b26f7e959946f289bd954ba93f4fd89

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
